### ISSUE TITLE
arguments for snyk test

### ISSUE THREAD

**Issue by kmplngj** [fabasoad/pre-commit-snyk#34]
Hello,

could you please add the option to add CLI arguments to the snyk test hook.

I want to set the severity-threshold.

Thanks for the work!

**Comment by fabasoad** [comment]
Hello! It is possible. Here is the example:

```yaml
- repo: https://github.com/fabasoad/pre-commit-snyk
  rev: v0.3.0
  hooks:
    - id: snyk-test
      args: ["--severity-threshold=critical"]
```

Let me know if it doesn't work for you.
